### ISSUE TITLE
suggestion for the upcoming firefox addon

### ISSUE THREAD

**Issue by elypter** [Jaxkr/Truthbot.org#11]
i found an addon that integrates ssl certificate ownership chain details in the dialog that opens if you click on the lock icon next to the url. i think it would be elegant if you could include the company ownership chain in the same dialog. it it also safe you time if you can look at how they did it.
https://addons.mozilla.org/en-US/firefox/addon/certificate-patrol/

**Comment by Jaxkr** [comment]
I think I'll probably just include the ownership details under a normal browser button as much of the Chrome source is compatible with Firefox already, just with some minor modifications. Thank you for the suggestion though. Any other feature requests?
